#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias gfmu='git pull upstream "$(git-branch-current 2> /dev/null)"'

# added by travis gem
[ -f /home/cnk/.travis/travis.sh ] && source /home/cnk/.travis/travis.sh
